#!/usr/bin/env python3
"""Fail-closed production gate for the official Engine toolchain output."""
import json, os, shutil, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MATH = Path(os.environ.get("NEON_MATH_GAME") or os.environ.get("ENGINE_MATH_GAME") or ROOT / "math/neon_dynasty")
WEB = Path(os.environ.get("NEON_WEB_GAME") or os.environ.get("ENGINE_WEB_GAME") or ROOT / "web/neon-dynasty")
checks=[]
def add(name, ok, detail): checks.append({"name":name,"ok":bool(ok),"detail":str(detail)})

add("python", sys.version_info >= (3,12), sys.version.split()[0])
add("node", shutil.which("node") is not None, shutil.which("node") or "missing")
add("pnpm", shutil.which("pnpm") is not None, shutil.which("pnpm") or "missing")
add("zstd", shutil.which("zstd") is not None, shutil.which("zstd") or "missing")
add("cargo", shutil.which("cargo") is not None, shutil.which("cargo") or "missing")

modes=("base","basic","super","mystery")
for mode in modes:
    p=MATH/"library/publish_files"/f"books_{mode}.jsonl.zst"
    add(f"publication_book_{mode}", p.is_file(), p)
    if p.is_file() and shutil.which("zstd"):
        proc=subprocess.Popen(["zstd","-dc",str(p)], stdout=subprocess.PIPE, text=True)
        rows=0
        if proc.stdout:
            for line in proc.stdout:
                if line.strip(): rows += 1
            proc.stdout.close()
        rc=proc.wait()
        add(f"100k_rows_{mode}", rc == 0 and rows >= 100000, f"{rows} rows")
    else:
        add(f"100k_rows_{mode}", False, "book unavailable or zstd missing")

# The official Web SDK currently emits .svelte-kit/output for built apps.
web_candidates=(WEB/".svelte-kit/output", WEB/"build", WEB/"dist")
existing=[p for p in web_candidates if p.exists()]
add("web_build_artifact", bool(existing), "; ".join(map(str,existing)) if existing else "missing")

# Reject known placeholder/sample assets only in the production web app tree.
sample_tokens=("sample_lines","sample_provider","symbols3","clusterpay","miningfont_","reelhouse_glow")
sample=[]
for p in WEB.rglob("*"):
    if p.is_file() and any(t in p.name.lower() for t in sample_tokens): sample.append(str(p.relative_to(WEB)))
add("sample_asset_quarantine", not sample, "; ".join(sample[:12]) if sample else "clean")

# Require the official optimizer evidence generated by the math SDK, rather than
# accepting only book counts. The exact filename can evolve; accept the current
# standard evidence locations if present.
evidence=[]
for p in (MATH/"library", MATH/"library/lookup_tables", MATH/"library/configs"):
    if p.exists():
        evidence.extend([x for x in p.rglob("*") if x.is_file() and any(k in x.name.lower() for k in ("stat", "analysis", "par", "verification"))])
add("optimizer_evidence", bool(evidence), "; ".join(str(x.relative_to(MATH)) for x in evidence[:12]) if evidence else "missing")

report={"build":"63","candidate_status":"production_candidate","production_certified":False,"checks":checks,"ready":all(c["ok"] for c in checks),"math_root":str(MATH),"web_root":str(WEB),"note":"Certification remains false until the official Engine optimizer, verification suite, and Web SDK build have all passed in a network-enabled toolchain."}
(ROOT/"RELEASE_GATE_BUILD_63.json").write_text(json.dumps(report,indent=2)+"\n")
print(json.dumps(report,indent=2))
sys.exit(0 if report["ready"] else 2)
