// Neon Dynasty original asset registry. No Engine sample runtime assets are referenced.
const svg = (path: string) => new URL(`../assets/neon/${path}`, import.meta.url).href;
const sprite = (path: string, preload = false) => ({ type: 'sprite', src: svg(path), ...(preload ? { preload: true } : {}) });

export default {
	loader: sprite('loader.svg', true),
	pressToContinueText: sprite('winsmall.svg'),
	H1: sprite('symbols/empress.svg'),
	H2: sprite('symbols/dragon.svg'),
	H3: sprite('symbols/fox.svg'),
	H4: sprite('symbols/tiger.svg'),
	H5: sprite('symbols/butterfly.svg'),
	L1: sprite('symbols/jade.svg'),
	L2: sprite('symbols/koi.svg'),
	L3: sprite('symbols/mask.svg'),
	L4: sprite('symbols/crane.svg'),
	M: sprite('symbols/empress.svg'),
	S: sprite('animations/S.svg'),
	explosion: sprite('animations/explosion.svg'),
	W: sprite('animations/W.svg'),
	reelsFrame: sprite('ui/neon-frame.svg'),
	payFrame: sprite('ui/neon-frame.svg'),
	anticipation: sprite('animations/anticipation.svg'),
	bigwin: sprite('animations/bigwin.svg'),
	globalMultiplier: sprite('animations/globalMultiplier.svg'),
	fsIntro: sprite('animations/fsIntro.svg'),
	fsIntroNumber: sprite('animations/fsIntroNumber.svg'),
	fsOutroNumber: sprite('animations/fsOutroNumber.svg'),
	foregroundAnimation: sprite('animations/foregroundAnimation.svg', true),
	foregroundFeatureAnimation: sprite('animations/foregroundFeatureAnimation.svg', true),
	tumble_multiplier: sprite('animations/tumble_multiplier.svg'),
	tumble_win: sprite('animations/tumble_win.svg'),
	reelhouse: sprite('animations/reelhouse.svg'),
	progressBar: sprite('ui/progressBar.svg', true),
	freeSpins: sprite('ui/freespins.svg'),
	winSmall: sprite('ui/winsmall.svg'),
	clusterWin: sprite('animations/clusterWin.svg'),
	transition: sprite('animations/transition.svg'),
	symbolsStatic: sprite('ui/neon-frame.svg'),
	coins: sprite('ui/coin.svg'),
	sound: { type: 'audio', src: new URL('../assets/neon/audio/sounds.json', import.meta.url).href, preload: true },
} as const;
